# This file is generated by init_gen.py. Do not edit.

from aserto.directory.schema.v2.identity_pb2 import (
    IdentityKind,
    IdentityProperties,
)

from aserto.directory.schema.v2.user_pb2 import (
    UserStatus,
    UserProperties,
)

__all__ = [
    "IdentityKind",
    "IdentityProperties",
    "UserStatus",
    "UserProperties",
]