# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aserto/directory/schema/v2/tenant.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'aserto/directory/schema/v2/tenant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'aserto/directory/schema/v2/tenant.proto\x12\x1a\x61serto.directory.schema.v2\x1a\x1cgoogle/protobuf/struct.proto\"\xfb\x01\n\x10TenantProperties\x12:\n\x04kind\x18\x01 \x01(\x0e\x32&.aserto.directory.schema.v2.TenantKindR\x04kind\x12!\n\x0c\x64irectory_v2\x18\x02 \x01(\x08R\x0b\x64irectoryV2\x12*\n\x11\x64irectory_v2_only\x18\x03 \x01(\x08R\x0f\x64irectoryV2Only\x12L\n\x07\x61\x63\x63ount\x18\x04 \x01(\x0b\x32-.aserto.directory.schema.v2.AccountPropertiesH\x00R\x07\x61\x63\x63ount\x88\x01\x01:\x02\x18\x01\x42\n\n\x08_account\"\xc8\x01\n\x11\x41\x63\x63ountProperties\x12\x19\n\x08max_orgs\x18\x01 \x01(\x05R\x07maxOrgs\x12T\n\x0fgetting_started\x18\x03 \x01(\x0b\x32&.aserto.directory.schema.v2.GuideStateH\x00R\x0egettingStarted\x88\x01\x01\x12*\n\x11\x64\x65\x66\x61ult_tenant_id\x18\x04 \x01(\tR\x0f\x64\x65\x66\x61ultTenantId:\x02\x18\x01\x42\x12\n\x10_getting_started\"S\n\nGuideState\x12\x12\n\x04show\x18\x01 \x01(\x08R\x04show\x12-\n\x05steps\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\x05steps:\x02\x18\x01*`\n\nTenantKind\x12\x17\n\x13TENANT_KIND_UNKNOWN\x10\x00\x12\x1c\n\x18TENANT_KIND_ORGANIZATION\x10\x01\x12\x17\n\x13TENANT_KIND_ACCOUNT\x10\x02\x1a\x02\x18\x01\x42\x80\x02\n\x1e\x63om.aserto.directory.schema.v2B\x0bTenantProtoP\x01ZDgithub.com/aserto-dev/go-directory/aserto/directory/schema/v2;schema\xa2\x02\x03\x41\x44S\xaa\x02\x1a\x41serto.Directory.Schema.V2\xca\x02\x1b\x41serto\\Directory_\\Schema\\V2\xe2\x02\'Aserto\\Directory_\\Schema\\V2\\GPBMetadata\xea\x02\x1d\x41serto::Directory::Schema::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aserto.directory.schema.v2.tenant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.aserto.directory.schema.v2B\013TenantProtoP\001ZDgithub.com/aserto-dev/go-directory/aserto/directory/schema/v2;schema\242\002\003ADS\252\002\032Aserto.Directory.Schema.V2\312\002\033Aserto\\Directory_\\Schema\\V2\342\002\'Aserto\\Directory_\\Schema\\V2\\GPBMetadata\352\002\035Aserto::Directory::Schema::V2'
  _globals['_TENANTKIND']._loaded_options = None
  _globals['_TENANTKIND']._serialized_options = b'\030\001'
  _globals['_TENANTPROPERTIES']._loaded_options = None
  _globals['_TENANTPROPERTIES']._serialized_options = b'\030\001'
  _globals['_ACCOUNTPROPERTIES']._loaded_options = None
  _globals['_ACCOUNTPROPERTIES']._serialized_options = b'\030\001'
  _globals['_GUIDESTATE']._loaded_options = None
  _globals['_GUIDESTATE']._serialized_options = b'\030\001'
  _globals['_TENANTKIND']._serialized_start=643
  _globals['_TENANTKIND']._serialized_end=739
  _globals['_TENANTPROPERTIES']._serialized_start=102
  _globals['_TENANTPROPERTIES']._serialized_end=353
  _globals['_ACCOUNTPROPERTIES']._serialized_start=356
  _globals['_ACCOUNTPROPERTIES']._serialized_end=556
  _globals['_GUIDESTATE']._serialized_start=558
  _globals['_GUIDESTATE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
