"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import aserto.directory.common.v3.common_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Option:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OptionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Option.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPTION_UNKNOWN: _Option.ValueType  # 0
    """nothing selected (default initialization value)"""
    OPTION_DATA_OBJECTS: _Option.ValueType  # 8
    """object instances"""
    OPTION_DATA_RELATIONS: _Option.ValueType  # 16
    """relation instances"""
    OPTION_DATA: _Option.ValueType  # 24
    """all data = OPTION_DATA_OBJECTS | OPTION_DATA_RELATIONS"""

class Option(_Option, metaclass=_OptionEnumTypeWrapper): ...

OPTION_UNKNOWN: Option.ValueType  # 0
"""nothing selected (default initialization value)"""
OPTION_DATA_OBJECTS: Option.ValueType  # 8
"""object instances"""
OPTION_DATA_RELATIONS: Option.ValueType  # 16
"""relation instances"""
OPTION_DATA: Option.ValueType  # 24
"""all data = OPTION_DATA_OBJECTS | OPTION_DATA_RELATIONS"""
global___Option = Option

@typing_extensions.final
class ExportRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPTIONS_FIELD_NUMBER: builtins.int
    START_FROM_FIELD_NUMBER: builtins.int
    options: builtins.int
    """data export options mask"""
    @property
    def start_from(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """start export from timestamp (UTC)"""
    def __init__(
        self,
        *,
        options: builtins.int = ...,
        start_from: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["start_from", b"start_from"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["options", b"options", "start_from", b"start_from"]) -> None: ...

global___ExportRequest = ExportRequest

@typing_extensions.final
class ExportResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    @property
    def object(self) -> aserto.directory.common.v3.common_pb2.Object:
        """object instance (data)"""
    @property
    def relation(self) -> aserto.directory.common.v3.common_pb2.Relation:
        """relation instance (data)"""
    def __init__(
        self,
        *,
        object: aserto.directory.common.v3.common_pb2.Object | None = ...,
        relation: aserto.directory.common.v3.common_pb2.Relation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["msg", b"msg", "object", b"object", "relation", b"relation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg", b"msg", "object", b"object", "relation", b"relation"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["object", "relation"] | None: ...

global___ExportResponse = ExportResponse
