name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
      proto_sha:
  push:
    branches:
      - main
      - v*
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for PRs
  pull_request:

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  GO_VERSION: "1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Read Configuration
      uses: hashicorp/vault-action@v2.4.1
      id: vault
      with:
        url: ${{ env.VAULT_ADDR }}
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/github  "SSH_PRIVATE_KEY"     | SSH_PRIVATE_KEY;
          kv/data/buf.build "ASERTO_BUF_TOKEN"  | ASERTO_BUF_TOKEN;

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Setup caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          .ext
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
          mkdir -p $HOME/.ssh
          umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts

          git config --global url."git@github.com:".insteadOf https://github.com/
          git config --global user.email "github-bot@aserto.com"
          git config --global user.name "Aserto Bot"

          eval `ssh-agent`
          ssh-add $HOME/.ssh/id_rsa

          go run mage.go deps

          poetry install --no-interaction

    - name: Clean generated code
      run: go run mage.go clean

    - name: Setup Buf Registry
      run: echo -e "machine buf.build\npassword ${ASERTO_BUF_TOKEN}" >> ~/.netrc

    - name: Generate
      run: poetry run go run mage.go generate

    - name: Commit changes
      if: github.event_name == 'workflow_dispatch'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: 'src'
        push: origin HEAD:main

    - name: Build the python package
      run: go run mage.go build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    name: Release to pypi
    steps:
      - name: Read Configuration
        uses: hashicorp/vault-action@v2.4.1
        id: vault
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/github  "SSH_PRIVATE_KEY"    | SSH_PRIVATE_KEY;
            kv/data/pypi  "PASSWORD" | POETRY_HTTP_BASIC_PYPI_USERNAME;
            kv/data/pypi  "USERNAME" | POETRY_HTTP_BASIC_PYPI_PASSWORD;

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            .ext
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', 'Depfile') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
            mkdir -p $HOME/.ssh
            umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
            ssh-keyscan github.com >> $HOME/.ssh/known_hosts

            git config --global url."git@github.com:".insteadOf https://github.com/
            git config --global user.email "github-bot@aserto.com"
            git config --global user.name "Aserto Bot"

            eval `ssh-agent`
            ssh-add $HOME/.ssh/id_rsa

            go run mage.go deps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build and push the python package
        run: go run mage.go release

      - name: Bump to the next version
        run: go run mage.go bump patch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Bump to next version'
          add: 'pyproject.toml'
          push: origin HEAD:main
